/** Mock parsed menus for testing the pure-TS funnel without hitting the API. */
import type { MenuItem } from '../src/lib/types';

export const SUSHI_MENU: MenuItem[] = [
  {
    id: 's1',
    name: 'Baked Salmon Roll',
    price: 14,
    description: 'Baked salmon, mild eel sauce, avocado',
    ingredients: ['salmon', 'rice', 'avocado', 'eel sauce'],
    flavor_profile: ['umami', 'savory'],
    texture: ['soft', 'creamy'],
    spice_level: 0,
    dietary_tags: ['halal'],
    protein_type: ['seafood'],
    cuisine_type: 'japanese',
  },
  {
    id: 's2',
    name: 'Spicy Tuna Roll',
    price: 12,
    description: 'Fresh tuna (maguro), spicy mayo, scallion',
    ingredients: ['tuna', 'rice', 'spicy mayo'],
    flavor_profile: ['umami', 'tangy'],
    texture: ['soft', 'fresh'],
    spice_level: 3,
    dietary_tags: ['halal'],
    protein_type: ['seafood'],
    cuisine_type: 'japanese',
  },
  {
    id: 's3',
    name: 'Shrimp Tempura Roll',
    price: 13,
    description: 'Crispy fried shrimp tempura, cucumber',
    ingredients: ['shrimp', 'rice', 'cucumber', 'tempura batter'],
    flavor_profile: ['savory', 'rich'],
    texture: ['crispy'],
    spice_level: 1,
    dietary_tags: [],
    protein_type: ['seafood'],
    cuisine_type: 'japanese',
  },
  {
    id: 's4',
    name: 'Yellowtail Sashimi',
    price: 16,
    description: 'Raw hamachi, sliced thin, fresh',
    ingredients: ['yellowtail'],
    flavor_profile: ['umami', 'rich'],
    texture: ['fresh', 'soft'],
    spice_level: 0,
    dietary_tags: ['halal', 'gluten-free'],
    protein_type: ['seafood'],
    cuisine_type: 'japanese',
  },
  {
    id: 's5',
    name: 'Albacore Nigiri',
    price: 11,
    description: 'White tuna over rice, raw',
    ingredients: ['albacore', 'rice'],
    flavor_profile: ['umami'],
    texture: ['soft', 'fresh'],
    spice_level: 0,
    dietary_tags: ['halal'],
    protein_type: ['seafood'],
    cuisine_type: 'japanese',
  },
];

export const DESI_MENU: MenuItem[] = [
  {
    id: 'd1',
    name: 'Chicken Karahi',
    price: 18,
    description: 'Wok-cooked karahi chicken, tomatoes, green chili',
    ingredients: ['chicken', 'tomato', 'chili', 'ginger'],
    flavor_profile: ['savory', 'tangy'],
    texture: ['soft'],
    spice_level: 4,
    dietary_tags: ['halal'],
    protein_type: ['chicken'],
    cuisine_type: 'pakistani',
  },
  {
    id: 'd2',
    name: 'Seekh Kebab',
    price: 14,
    description: 'Tandoori minced beef seekh kebab, grilled',
    ingredients: ['beef', 'onion', 'spices'],
    flavor_profile: ['smoky', 'savory'],
    texture: ['soft'],
    spice_level: 3,
    dietary_tags: ['halal'],
    protein_type: ['beef'],
    cuisine_type: 'pakistani',
  },
  {
    id: 'd3',
    name: 'Beef Nihari',
    price: 17,
    description: 'Slow cooked beef shank stew, rich gravy',
    ingredients: ['beef', 'flour', 'spices'],
    flavor_profile: ['rich', 'savory'],
    texture: ['soft', 'creamy'],
    spice_level: 2,
    dietary_tags: ['halal'],
    protein_type: ['beef'],
    cuisine_type: 'pakistani',
  },
  {
    id: 'd4',
    name: 'Chicken Tikka',
    price: 15,
    description: 'Tandoor grilled chicken tikka, charred',
    ingredients: ['chicken', 'yogurt', 'spices'],
    flavor_profile: ['smoky'],
    texture: ['soft', 'crispy'],
    spice_level: 3,
    dietary_tags: ['halal'],
    protein_type: ['chicken'],
    cuisine_type: 'pakistani',
  },
  {
    id: 'd5',
    name: 'Chicken Biryani',
    price: 16,
    description: 'Layered basmati pulao with spiced chicken',
    ingredients: ['chicken', 'rice', 'spices'],
    flavor_profile: ['savory', 'rich'],
    texture: ['soft'],
    spice_level: 2,
    dietary_tags: ['halal'],
    protein_type: ['chicken'],
    cuisine_type: 'pakistani',
  },
  {
    id: 'd6',
    name: 'Lamb Korma',
    price: 19,
    description: 'Creamy korma with tender lamb',
    ingredients: ['lamb', 'cream', 'cashew', 'spices'],
    flavor_profile: ['rich', 'creamy'],
    texture: ['creamy', 'soft'],
    spice_level: 1,
    dietary_tags: ['halal'],
    protein_type: ['lamb'],
    cuisine_type: 'pakistani',
  },
];
